### PR TITLE
Add info about data sent to IBM services in help

### PR DESCRIPTION
**Pull request by kevinrobinson**
This is trying to help out with https://github.com/IBM/taxinomitis/issues/172.

@dalelane As a first step, this updates the help in the bit I discovered looking at recognizing text, and IBM Watson Assistant.  I tried to run the app locally to grab a proper screenshot for ya but I don't have accounts for all the dependencies like Auth0 or Watson so wasn't sure what to do there.  Hopefully I've followed your example and this work just like it appears :)

### CODE REVIEW

**Comment by dalelane** [comment]
Thanks very much for this. I'm super-busy this week, so will review/merge over the weekend.

**Comment by ajdaniel** [comment]
This looks like a good start to address any questions kids, parents or teachers may have around privacy in the site.

**Comment by dalelane** [comment]
Thanks for this. Sorry, but there are a few things I'd like to change about this, so I'll start a new pull request to put it in - as I don't have access to your fork.

**Comment by kevinrobinson** [comment]
@dalelane no worries, sounds good!

**Comment by dalelane** [comment]
Added it in https://github.com/IBM/taxinomitis/commit/4210e677ac7c50f8831c15b302bd270e2fc4cae9

The main differences:
- Added it to all language files, not just the English file (that is useful for translators so they only have one place to look for what needs translating, rather than needing to keep the different language files in sync themselves - it also means the build passes, as there are automated tests at build time which make sure that there is nothing in any one NLS file that is missing from any other language NLS files)
- Added Visual Recognition links as well as Watson Assistant - to cover both image and text projects (I think that for some parents/teachers, they may have more concern about image training data than for text training, as this could contain photos of the children themselves if they use webcams to collect training images - so I wanted to make sure both were included)
- Added a clarification that as the DB administrator, I have access to all the raw data, but that I don't allow others to access it and won't share/publish it 
- Modified the HTML to split it out into it's own question rather than having it run-on from the user info question

**Comment by kevinrobinson** [comment]
@dalelane This looks awesome, and much better than my attempt! 👍

**Pull request closed without merging**
