### PR TITLE
add cn.json for Simplified Chinese translation

### PR DESCRIPTION
**Pull request by Jaapin**

### CODE REVIEW

**Comment by dalelane** [comment]
@Jaapin This is fantastic, thank you so much for contibuting this!

I've added this to the site at https://machinelearningforkids.co.uk/?lang=testing-cn 
Would you mind giving that a look over and checking that it all looks okay, please?
If you think it looks okay, I can remove the 'testing' bit.

**Comment by Jaapin** [comment]
> @Jaapin This is fantastic, thank you so much for contibuting this!
> 
> I've added this to the site at https://machinelearningforkids.co.uk/?lang=testing-cn
> Would you mind giving that a look over and checking that it all looks okay, please?
> If you think it looks okay, I can remove the 'testing' bit.

@dalelane 
After previewing https://machine learning for children.co.uk/?Lang=testing-cn, I fixed some inappropriate translations. Most of them can browse normally. There are still some minor problems, such as  :
taxinomiti_cn_trans
. the description does not find the corresponding translation.

**Comment by Jaapin** [comment]
@dalelane
After previewing https://machine learning for children.co.uk/?Lang=testing-cn, I fixed some inappropriate translations. Most of them can browse normally. There are still some minor problems, such as pictures in the attachment: the description does not find the corresponding translation.


liaojiaping@aliyun.com
 
From: Dale Lane
Date: 2018-10-27 05:03
To: IBM/taxinomitis
CC: Jaapin; Mention
Subject: Re: [IBM/taxinomitis] add cn.json for Simplified Chinese translation (#102)
@Jaapin This is fantastic, thank you so much for contibuting this!
I've added this to the site at https://machinelearningforkids.co.uk/?lang=testing-cn
Would you mind giving that a look over and checking that it all looks okay, please?
If you think it looks okay, I can remove the 'testing' bit.

**Comment by dalelane** [comment]
@Jaapin You're right that the translation support was missing for the Scratch page. I've fixed that now at https://github.com/IBM/taxinomitis/blob/df520716350e4898ac638861562ee8df1b29cde4/public/languages/zh-cn.json#L442-L455

**Pull request merged**
